namespace SqlOptimizer.Application.DTOs;

/// <summary>
/// Origin of an <see cref="OptimizationCandidate"/>. The source only records
/// where the candidate text came from; it never records whether the candidate
/// is safe. Semantic safety is decided exclusively by <c>ISqlValidator</c>.
/// </summary>
public enum CandidateSource
{
    /// <summary>Generated deterministically from rule engine evidence.</summary>
    Rule,

    /// <summary>Generated by an LLM provider (untrusted until validated).</summary>
    Llm
}
